bookmarks/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'bookmarks', views.BookmarkViewSet)
router.register(r'folders', views.FolderViewSet)

urlpatterns = [
    path('list/', views.FolderListView.as_view(), name='list'),
    re_path(r'^list/(?P<display>cards?)', views.FolderListView.as_view(),
            name='index'),
    path('detail/<int:pk>', views.FolderDetailView.as_view(), name='detail'),
    re_path('detail/<int:pk>(?P<display>cards?)',
            views.FolderDetailView.as_view(), name='detail'),
    path('extension/', views.extension, name='extension'),
    path('api/', include(router.urls)),
]

bookmarks/models.py
from django.db import models

# Create your models here.

class Folder(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=16)

    class Meta:
        ordering = ['name']

class Bookmark(models.Model):
    id = models.AutoField(primary_key=True)
    pageLink = models.CharField(max_length=512)
    pageTitle = models.CharField(max_length=128)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to='bookmarks/thumbnails',
                                  default='blank.svg')

bookmarks/views.py
from django.middleware import csrf
from django.http import HttpResponse
from django.views import generic
from django.conf import settings
from django.utils.module_loading import import_string
from rest_framework import viewsets
import json

from .models import Folder, Bookmark
from .serializers import BookmarkSerializer, FolderSerializer

AuthMixin = import_string(
    getattr(settings, 'BOOKMARKS_AUTH_MIXIN',
            'django.contrib.auth.mixins.UserPassesTestMixin')
)

class FolderDetailView(AuthMixin, generic.DetailView):
    model = Folder

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display'] = self.request.GET.get('display', 'list')
        if context['display'] != 'cards' and context['display'] != 'list':
            context['display'] = 'list'
        return context

    def test_func(self):
        # If this is defined, we don't want to allow access
        return not hasattr(settings, 'BOOKMARKS_AUTH_MIXIN')

class FolderListView(AuthMixin, generic.ListView):
    model = Folder

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display'] = self.request.GET.get('display', 'list')
        if context['display'] != 'cards' and context['display'] != 'list':
            context['display'] = 'list'
        return context

    def test_func(self):
        # If this is defined, we don't want to allow access
        return not hasattr(settings, 'BOOKMARKS_AUTH_MIXIN')

def extension(request):
    return HttpResponse(json.dumps({'token': csrf.get_token(request)}),
                        content_type='application/json')

###############################################################################
# Django REST Framework API Views
###

class BookmarkViewSet(viewsets.ModelViewSet):
    """API endpoint that allows bookmarks to be viewed or edited."""
    authentication_classes = getattr(settings, 'BOOKMARKS_AUTH_CLASSES', [])
    permission_classes = getattr(settings, 'BOOKMARKS_PERM_CLASSES', [])
    queryset = Bookmark.objects.all()
    serializer_class = BookmarkSerializer

class FolderViewSet(viewsets.ModelViewSet):
    """API endpoint that allows folders to be viewed or edited."""
    authentication_classes = getattr(settings, 'BOOKMARKS_AUTH_CLASSES', [])
    permission_classes = getattr(settings, 'BOOKMARKS_PERM_CLASSES', [])
    queryset = Folder.objects.all()
    serializer_class = FolderSerializer

###############################################################################

bookmarks/templates/bookmarks/application_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    {% load static %}
    <link rel="shortcut icon" sizes="any" type="image/svg+xml" href="{% static 'bookmarks/images/favicon.svg' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'bookmarks/css/style.css' %}" />
    <title>Bookmarks</title>
  </head>
  <body class="bg-dark text-white">
    <div class="form-overlay">
      <div id="new-folder-form" class="form">
        <h5>Add a new Folder</h5>
        <form action="">
          <div class="form-input-group">
            <label for="name">Name</label>
            <input name="name" type="text" value="" placeholder="Folder Name"/>
          </div>
          <div class="form-submit-group">
            <button class="btn btn-dark submit okay">Okay</button>
            <button class="btn btn-dark submit cancel">Cancel</button>
          </div>
        </form>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row vh-100">
        <div id="nav-column" class="col-3 col-lg-2 px-0 bg-real-dark">
          <nav class="navbar navbar-dark bg-real-dark text-white sticky-top">
            <div class="navbar-nav">
              <div class="row">
                <h4>Folders</h4>
                <div id="new-folder-button" href="#">
                  <img alt="new folder"
                       src="{% static 'bookmarks/images/new-folder.svg' %}"/>
                </div>
              </div>
              <div id="folder-list">
                {% if folder_list %}
                {% for folder in folder_list %}
                <a class="nav-link active"
                   href="#folder-{{ folder.name|lower }}">{{ folder.name }}</a>
                {% endfor %}
                {% endif %}
              </div>
            </div>
          </nav>
        </div>

        <main class="col-9 col-lg-10 border-left border-dark min-vh-100">
          {% block content %}
          {% endblock %}
        </main>
        <footer>
          <div class="footer-content">
            <p>Bookmarks, &copy; Ethan D.
              Twardy 2020. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </div>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

bookmarks/templates/bookmarks/display_cards.html
<div class="folder-grid">
  {% load static %}
  {% for bookmark in folder.bookmark_set.all %}
  <div id="bookmark-{{ bookmark.pk }}"
       class="card bg-real-dark mb-3 mr-3">
    <input
      name="bookmark-url" type="hidden"
      value="{{ request.path }}api/bookmarks/{{ bookmark.id }}/"/>
    {% ifequal bookmark.thumbnail.name 'blank.svg' %}
    <img
      class="card-img-top" alt="Card image cap"
      src="{% static 'bookmarks/images/blankThumbnail.svg' %}"/>
    {% else %}
    <img class="card-img-top" alt="Card image cap"
         src="{{ bookmark.thumbnail.url }}"/>
    {% endifequal %}
    <div class="card-body py-2">
      <p class="mb-2">{{ bookmark.pageTitle }}</p>
      <div class="action-container">
        <a class="btn btn-outline-light" target="_blank"
           href="{{ bookmark.pageLink }}">Visit</a>
        <div class="button-transitioner">
          <img class="btn delete bottom" alt="delete" src="{% static 'bookmarks/images/white-delete.svg' %}"/>
          <img class="btn delete top" alt="delete" src="{% static 'bookmarks/images/white-delete-filled.svg' %}"/>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

bookmarks/templates/bookmarks/display_list.html
<ul class="list-group">
  {% load static %}
  {% for bookmark in folder.bookmark_set.all %}
  <li id="bookmark-{{ bookmark.pk }}"class="list-group-item list-group-item-dark d-flex justify-content-between align-items-center py-1">{{ bookmark.pageTitle }}
    <input
      name="bookmark-url" type="hidden"
      value="{{ request.path }}api/bookmarks/{{ bookmark.id }}/"/>
    <div class="action-container">
      <a class="btn btn-outline-dark" target="_blank"
         href="{{ bookmark.pageLink }}">Visit</a>
      <div class="button-transitioner">
        <img class="btn delete bottom" alt="delete"
             src="{% static 'bookmarks/images/delete.svg' %}"/>
        <img
          class="btn delete top" alt="delete"
          src="{% static 'bookmarks/images/delete-filled.svg' %}"/>
      </div>
    </div>
  </li>
  {% endfor %}
</ul>

bookmarks/templates/bookmarks/folder_detail.html
{% extends "bookmarks/application_base.html" %}
{% block content %}
<h2 class="mt-2 mb-4">Bookmarks</h2>
<div class="container" id="bookmark-container">
  {% csrf_token %}
  {% if folder %}
  <div class="folder pb-5" id="folder-{{ folder.name|lower }}">
    <h5 class="folder-title">{{ folder.name }}</h5>
    {% ifequal display 'list' %}
    {% include 'bookmarks/display_list.html' %}
    {% else %}
    {% include 'bookmarks/display_cards.html' %}
    {% endifequal %}
  </div>
  {% else %}
  <p>You have no bookmarks yet!</p>
  {% endif %}

</div>
{% endblock %}

{% block scripts %}
{% load static %}
<script src="{% static 'bookmarks/js/bundle.js' %}"></script>
{% endblock %}

bookmarks/templates/bookmarks/folder_list.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    {% load static %}
    <link rel="shortcut icon" sizes="any" type="image/svg+xml" href="{% static 'bookmarks/images/favicon.svg' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'bookmarks/css/style.css' %}" />
    <title>Bookmarks</title>
  </head>
  <body class="bg-dark text-white">
    <div class="form-overlay">
      <div id="new-folder-form" class="form">
        <h5>Add a new Folder</h5>
        <form action="">
          <div class="form-input-group">
            <label for="name">Name</label>
            <input name="name" type="text" value="" placeholder="Folder Name"/>
          </div>
          <div class="form-submit-group">
            <button class="btn btn-dark submit okay">Okay</button>
            <button class="btn btn-dark submit cancel">Cancel</button>
          </div>
        </form>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row vh-100">
        <div id="nav-column" class="col-3 col-lg-2 px-0 bg-real-dark">
          <nav class="navbar navbar-dark bg-real-dark text-white sticky-top">
            <div class="navbar-nav">
              <div class="row">
                <h4>Folders</h4>
                <div id="new-folder-button" href="#">
                  <img alt="new folder" src="{% static 'bookmarks/images/new-folder.svg' %}"/>
                </div>
              </div>
              <div id="folder-list">
                {% if folder_list %}
                {% for folder in folder_list %}
                <a class="nav-link active" href="#folder-{{ folder.name|lower }}">{{ folder.name }}</a>
                {% endfor %}
                {% endif %}
              </div>
            </div>
          </nav>
        </div>

        <main class="col-9 col-lg-10 border-left border-dark min-vh-100">
          <h2 class="mt-2 mb-4">Bookmarks</h2>
          <div class="container" id="bookmark-container">
            {% csrf_token %}
            {% if folder_list %}
            {% for folder in folder_list %}
            <div class="folder pb-5" id="folder-{{ folder.name|lower }}">
              <h5 class="folder-title">{{ folder.name }}</h5>
              {% ifequal display 'list' %}
              <ul class="list-group">
                {% for bookmark in folder.bookmark_set.all %}
                <li id="bookmark-{{ bookmark.pk }}"class="list-group-item list-group-item-dark d-flex justify-content-between align-items-center py-1">{{ bookmark.pageTitle }}
                <input name="bookmark-url" type="hidden" value="{{ request.path }}api/bookmarks/{{ bookmark.id }}/"/>
                <div class="action-container">
                  <a class="btn btn-outline-dark" target="_blank" href="{{ bookmark.pageLink }}">Visit</a>
                  <div class="button-transitioner">
                    <img class="btn delete bottom" alt="delete" src="{% static 'bookmarks/images/delete.svg' %}"/>
                    <img class="btn delete top" alt="delete" src="{% static 'bookmarks/images/delete-filled.svg' %}"/>
                  </div>
                </div>
                </li>
                {% endfor %}
              </ul>

              {% else %}
              <div class="folder-grid">
              {% for bookmark in folder.bookmark_set.all %}
              <div id="bookmark-{{ bookmark.pk }}" class="card bg-real-dark mb-3 mr-3">
                <input name="bookmark-url" type="hidden" value="{{ request.path }}api/bookmarks/{{ bookmark.id }}/"/>
                {% ifequal bookmark.thumbnail.name 'blank.svg' %}
                <img class="card-img-top" src="{% static 'bookmarks/images/blankThumbnail.svg' %}" alt="Card image cap"/>
                {% else %}
                <img class="card-img-top" src="{{ bookmark.thumbnail.url }}" alt="Card image cap"/>
                {% endifequal %}
                <div class="card-body py-2">
                  <p class="mb-2">{{ bookmark.pageTitle }}</p>
                  <div class="action-container">
                    <a class="btn btn-outline-light" target="_blank" href="{{ bookmark.pageLink }}">Visit</a>
                    <div class="button-transitioner">
                      <img class="btn delete bottom" alt="delete" src="{% static 'bookmarks/images/white-delete.svg' %}"/>
                      <img class="btn delete top" alt="delete" src="{% static 'bookmarks/images/white-delete-filled.svg' %}"/>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              </div>
              {% endifequal %}
            </div>
            {% endfor %}
            {% else %}
            <p>You have no bookmarks yet!</p>
            {% endif %}

          </div>
        </main>
        <footer>
          <div class="footer-content">
            <p>Bookmarks, &copy; Ethan D.
            Twardy 2020. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </div>

    <script src="{% static 'bookmarks/js/bundle.js' %}"></script>
  </body>
</html>

templates/bookmarks/folder_list.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    {% load static %}
    <link rel="shortcut icon" sizes="any" type="image/svg+xml" href="{% static "images/favicon.svg" %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
    <title>Bookmarks</title>
  </head>
  <body class="bg-dark text-white">
    <div class="form-overlay">
      <div id="new-folder-form" class="form">
        <h5>Add a new Folder</h5>
        <form action="">
          <div class="form-input-group">
            <label for="name">Name</label>
            <input name="name" type="text" value="" placeholder="Folder Name"/>
          </div>
          <div class="form-submit-group">
            <button class="btn btn-dark submit okay">Okay</button>
            <button class="btn btn-dark submit cancel">Cancel</button>
          </div>
        </form>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row vh-100">
        <div id="nav-column" class="col-3 col-lg-2 px-0 bg-real-dark">
          <nav class="navbar navbar-dark bg-real-dark text-white sticky-top">
            <div class="navbar-nav">
              <div class="row">
                <h4>Folders</h4>
                <div id="new-folder-button" href="#">
                  <img alt="new folder" src="{% static "images/new-folder.svg" %}"/>
                </div>
              </div>
              <div id="folder-list">
                {% if folder_list %}
                {% for folder in folder_list %}
                <a class="nav-link active" href="#folder-{{ folder.name|lower }}">{{ folder.name }}</a>
                {% endfor %}
                {% endif %}
              </div>
            </div>
          </nav>
        </div>

        <main class="col-9 col-lg-10 border-left border-dark">
          <h2 class="mt-2 mb-4">Bookmarks</h2>
          <div class="container" id="bookmark-container">
            {% csrf_token %}
            {% if folder_list %}
            {% for folder in folder_list %}
            <div class="folder pb-5" id="folder-{{ folder.name|lower }}">
              <h5 class="folder-title">{{ folder.name }}</h5>
              {% ifequal display 'list' %}
              <ul class="list-group">
                {% for bookmark in folder.bookmark_set.all %}
                <li id="bookmark-{{ bookmark.pk }}"class="list-group-item list-group-item-dark d-flex justify-content-between align-items-center py-1">{{ bookmark.pageTitle }}
                <div class="action-container">
                  <a class="btn btn-outline-dark" target="_blank" href="{{ bookmark.pageLink }}">Visit</a>
                  <div class="button-transitioner">
                    <img class="btn delete bottom" alt="delete" src="{% static "images/delete.svg" %}"/>
                    <img class="btn delete top" alt="delete" src="{% static "images/delete-filled.svg" %}"/>
                  </div>
                </div>
                </li>
                {% endfor %}
              </ul>

              {% else %}
              <div class="folder-grid">
              {% for bookmark in folder.bookmark_set.all %}
              <div id="bookmark-{{ bookmark.pk }}" class="card bg-real-dark mb-3 mr-3">
                {% ifequal bookmark.thumbnail.name 'blank.svg' %}
                <img class="card-img-top" src="{% static 'images/blankThumbnail.svg' %}" alt="Card image cap"/>
                {% else %}
                <img class="card-img-top" src="{{ bookmark.thumbnail.url }}" alt="Card image cap"/>
                {% endifequal %}
                <div class="card-body py-2">
                  <p class="mb-2">{{ bookmark.pageTitle }}</p>
                  <div class="action-container">
                    <a class="btn btn-outline-light" target="_blank" href="{{ bookmark.pageLink }}">Visit</a>
                    <div class="button-transitioner">
                      <img class="btn delete bottom" alt="delete" src="{% static "images/white-delete.svg" %}"/>
                      <img class="btn delete top" alt="delete" src="{% static "images/white-delete-filled.svg" %}"/>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              </div>
              {% endifequal %}
            </div>
            {% endfor %}
            {% else %}
            <p>You have no bookmarks yet!</p>
            {% endif %}

          </div>
        </main>
        <footer>
          <div class="footer-content">
            <p>Bookmarks, &copy; Ethan D.
            Twardy 2020. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </div>

    <script src="{% static "js/build/bundle.js" %}"></script>
  </body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    {% load static %}
    <link rel="shortcut icon" sizes="any" type="image/svg+xml" href="{% static "images/favicon.svg" %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
    <title>Bookmarks</title>
  </head>
  <body class="bg-dark text-white">
    <div class="form-overlay">
      <div id="new-folder-form" class="form">
        <h5>Add a new Folder</h5>
        <form action="">
          <div class="form-input-group">
            <label for="name">Name</label>
            <input name="name" type="text" value="" placeholder="Folder Name"/>
          </div>
          <div class="form-submit-group">
            <button class="btn btn-dark submit okay">Okay</button>
            <button class="btn btn-dark submit cancel">Cancel</button>
          </div>
        </form>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row vh-100">
        <div id="nav-column" class="col-3 px-0 bg-real-dark">
          <nav class="navbar navbar-dark bg-real-dark text-white sticky-top">
            <div class="navbar-nav">
              <div class="row">
                <h4>Folders</h4>
                <div id="new-folder-button" href="#">
                  <img alt="new folder" src="{% static "images/new-folder.svg" %}"/>
                </div>
              </div>
              <div id="folder-list">
                {% if folderList %}
                {% for folder in folderList %}
                <a class="nav-link active" href="#folder-{{ folder.name|lower }}">{{ folder.name }}</a>
                {% endfor %}
                {% endif %}
              </div>
            </div>
          </nav>
        </div>

        <main class="col-9 border-left border-dark">
          <h2 class="mt-2 mb-4">Bookmarks</h2>
          <div class="container" id="bookmark-container">
            {% csrf_token %}
            {% if folderList %}
            {% for folder in folderList %}
            <div class="folder pb-5" id="folder-{{ folder.name|lower }}">
              <h5 class="folder-title">{{ folder.name }}</h5>
              {% ifequal display 'list' %}
              <ul class="list-group">
                {% for bookmark in folder.bookmarks %}
                <li id="bookmark-{{ bookmark.pk }}"class="list-group-item list-group-item-dark d-flex justify-content-between align-items-center py-1">{{ bookmark.pageTitle }}
                <div class="action-container">
                  <a class="btn btn-outline-dark" target="_blank" href="{{ bookmark.pageLink }}">Visit</a>
                  <div class="button-transitioner">
                    <img class="btn delete bottom" alt="delete" src="{% static "images/delete.svg" %}"/>
                    <img class="btn delete top" alt="delete" src="{% static "images/delete-filled.svg" %}"/>
                  </div>
                </div>
                </li>
                {% endfor %}
              </ul>
              {% else %}
              {% for bookmark in folder.bookmarks %}
              <div id="bookmark-{{ bookmark.pk }}" class="card bg-real-dark mb-3">
                <img class="card-img-top" src="{% static 'images/loadingThumbnail.svg' %}" alt="Card image cap"/>
                <div class="card-body py-2">
                  <p class="mb-2">{{ bookmark.pageTitle }}</p>
                  <div class="action-container">
                    <a class="btn btn-outline-dark" target="_blank" href="{{ bookmark.pageLink }}">Visit</a>
                    <div class="button-transitioner">
                      <img class="btn delete bottom" alt="delete" src="{% static "images/delete.svg" %}"/>
                      <img class="btn delete top" alt="delete" src="{% static "images/delete-filled.svg" %}"/>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              {% endifequal %}
            </div>
            {% endfor %}
            {% else %}
            <p>You have no bookmarks yet!</p>
            {% endif %}

          </div>
        </main>
        <footer>
          <div class="footer-content">
            <p>Bookmarks, &copy; Ethan D.
            Twardy 2020. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </div>

    <script src="{% static "js/build/bundle.js" %}"></script>
  </body>
</html>